services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8000:8000"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb
    environment:
      HODLBOOK_DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    ports:
      - "8080:8000"
